### ISSUE TITLE
self.updateDom error

### ISSUE THREAD

**Issue by robertraspberry** [georg90/MMM-HH-LocalTransport#3]
Hello, i've got this error if i start npm:

TypeError: self.updateDom is not a function
    at /home/pi/MagicMirror/modules/MMM-HH-LocalTransport/node_helper.js:61:14
    at Request.handleRequestResponse [as _callback](/home/pi/MagicMirror/modules/MMM-HH-LocalTransport/node_modules/unirest/index.js:355:15)
    at self.callback (/home/pi/MagicMirror/modules/MMM-HH-LocalTransport/node_modules/request/request.js:187:22)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:188:7)
    at Request.onRequestError (/home/pi/MagicMirror/modules/MMM-HH-LocalTransport/node_modules/request/request.js:813:8)
    at emitOne (events.js:96:13)
    at ClientRequest.emit (events.js:188:7)
    at Socket.socketErrorListener (_http_client.js:308:9)
    at emitOne (events.js:96:13)

do you have an idea to solve? Thanks in advance!
Best Regards an excited user of migaic mirror

**Comment by georg90** [comment]
closing this, because latest commits worked fine. Please reopen, when still valid.
